create or replace view urms_staging.kroger_division_level__normalized as
with final as (select * from urms_staging.urms_sample_data__normalized)
select

    sales_report_id,
    location_id,
    time_id,
    time_period_id,
    product_id,

    extract_end_date,
    time_start,
    time_end,
    time_type,
    time_period_name,
    time_period_type,
    time_period_start,
    time_period_end,
    viz_date,

    'Kroger' as retailer_name,
    null as store_name,
    market_name,
    null as warehouse_name,
    retailer_division,
    null as retailer_store_id,
    null as address1,
    null as address2,
    null as city,
    null as state,
    null as country,
    null as zipcode,
    false as is_store_level,
    false as is_warehouse_level,
    true as is_market_level,
    listing_sku,
    null as master_sku,
    'upc' as reporting_level,
    product_name,
    upc,
    brand_name,
    department,
    category,
    subcategory,
    product_class,
    null as product_type,
    null as product_size,
    null as unit_of_measure,
    1 as pack_count,
    dollar_sales,
    unit_sales,
    null as max_acv,
    null as tdp,
    null as number_of_weeks_selling,
    null as dollars_promo,
    null as units_promo,
    null as base_dollars,
    null as base_units,
    no_of_stores_selling,
    null as dollars_display_only,
    null as dollars_feature_only,
    null as dollars_feature_and_display,
    null as dollars_tpr,
    null as base_dollars_promo,
    null as base_units_promo,
    __file_name,
    __sync_key,
    'kroger_division_level' as __source_id,
    'Kroger Division Level' as __source_display_name,
    __synced_at
from final
where time_type = 'weekly'
;

